[build]
  command = "NEXT_PUBLIC_NETLIFY=$NETLIFY npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[context.production.environment]
  TOML_ENV_VAR = "production-toml-env-var"
  
[context.deploy-preview.environment]
  TOML_ENV_VAR = "deploy-preview-toml-env-var"

[context.branch-deploy.environment]
  TOML_ENV_VAR = "branch-deploy-toml-env-var"

[context.dev.environment]
  TOML_ENV_VAR = "dev-deploy-toml-env-var"
